
default: &default  
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:  
  adapter: postgresql  
  encoding: unicode  
  username: postgres  
  password:  
  pool: 5  
  host: db 
  database: app_name_production

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
